# Generated by Django 4.1.7 on 2023-04-17 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_settings", "0008_alter_badge_created_alter_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 17, 7, 44, 42, 119923, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 17, 7, 44, 42, 121998, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
