# Generated by Django 4.1.7 on 2023-04-18 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profile_settings",
            "0015_alter_badge_created_alter_reviewrating_created_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 18, 5, 14, 48, 75766, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 18, 5, 14, 48, 77715, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
