# Generated by Django 4.1.7 on 2023-05-22 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profile_settings",
            "0031_alter_stillneedhelp_options_alter_badge_created_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 22, 8, 52, 31, 701152, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 22, 8, 52, 31, 703462, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
