# Generated by Django 4.1.7 on 2023-04-09 10:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_alter_post_created_alter_postlist_created'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.ForeignKey(db_column='Service Type', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.category'),
        ),
        migrations.AddField(
            model_name='servicelocation',
            name='service_location',
            field=models.ForeignKey(db_column='Service Location', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_locations', to='lead.location'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 10, 46, 51, 159083, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 10, 46, 51, 143473, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 10, 46, 51, 143473, tzinfo=datetime.timezone.utc)),
        ),
    ]
