# Generated by Django 4.1.7 on 2023-04-18 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_alter_emailtemplate_created_alter_service_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicelocation",
            options={"ordering": ["id"], "verbose_name_plural": "Service Locations"},
        ),
        migrations.RenameField(
            model_name="servicelocation",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="servicelocation",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="servicelocation",
            name="service_location",
        ),
        migrations.AddField(
            model_name="servicelocation",
            name="latitude",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="servicelocation",
            name="longitude",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 18, 17, 48, 9, 467743, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 18, 17, 48, 9, 466262, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="servicelocation",
            name="city",
            field=models.CharField(db_column="postal_code_or_city", max_length=255),
        ),
        migrations.AlterField(
            model_name="servicelocation",
            name="distance",
            field=models.CharField(db_column="distance", max_length=255),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 18, 17, 48, 9, 467311, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterModelTable(
            name="servicelocation",
            table="service_location",
        ),
    ]
