# Generated by Django 4.1.7 on 2023-05-05 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_alter_emailtemplate_created_alter_service_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="service",
            name="created",
        ),
        migrations.AddField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 5, 11, 56, 14, 678454, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="servicelocation",
            name="service",
            field=models.ManyToManyField(
                related_name="services_location", to="account.service"
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 5, 11, 56, 14, 680737, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 5, 11, 56, 14, 680178, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
