# Generated by Django 4.1.7 on 2023-05-07 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0025_alter_emailtemplate_created_alter_service_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="updated_at",
            new_name="updated",
        ),
        migrations.RemoveField(
            model_name="service",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="servicelocation",
            name="service",
        ),
        migrations.AddField(
            model_name="service",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 9, 26, 23, 661718, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="service_location",
            field=models.ManyToManyField(
                related_name="services_location", to="account.servicelocation"
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 9, 26, 23, 663289, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 9, 26, 23, 662827, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
