# Generated by Django 4.1.7 on 2023-05-07 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0028_alter_emailtemplate_created_alter_service_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="service",
            name="created",
        ),
        migrations.AddField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 9, 33, 27, 143620, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 9, 33, 27, 145438, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 9, 33, 27, 144701, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
