# Generated by Django 4.1.7 on 2023-05-07 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0031_rename_service_location_service_service_locations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="service_locations",
        ),
        migrations.AddField(
            model_name="service",
            name="service_location",
            field=models.ManyToManyField(to="account.servicelocation"),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 9, 53, 31, 908562, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 9, 53, 31, 906911, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 9, 53, 31, 908094, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
