# Generated by Django 4.1.7 on 2023-05-07 18:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0034_alter_emailtemplate_created_alter_service_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="servicelocation",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services_id",
                to="account.service",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 18, 6, 4, 198644, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 18, 6, 4, 197616, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.RemoveField(
            model_name="service",
            name="service_location",
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 18, 6, 4, 198133, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="service_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_id",
                to="account.servicelocation",
            ),
        ),
    ]
