# Generated by Django 4.1.7 on 2023-05-07 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0035_servicelocation_service_alter_emailtemplate_created_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="service_location",
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 18, 8, 51, 997326, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 18, 8, 51, 995620, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 18, 8, 51, 996479, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
