# Generated by Django 4.1.7 on 2023-05-07 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0037_alter_emailtemplate_created_alter_service_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicelocation",
            name="service",
        ),
        migrations.AddField(
            model_name="service",
            name="service_location",
            field=models.ManyToManyField(to="account.servicelocation"),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 18, 43, 17, 644612, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 18, 43, 17, 641874, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 18, 43, 17, 643846, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
