# Generated by Django 4.1.7 on 2023-05-08 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0038_remove_servicelocation_service_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={"ordering": ["id"], "verbose_name_plural": "Email Templates"},
        ),
        migrations.AlterModelOptions(
            name="oneclickresponse",
            options={"ordering": ["id"], "verbose_name_plural": "One Click  Response"},
        ),
        migrations.AlterModelOptions(
            name="profilepicture",
            options={"ordering": ["id"], "verbose_name_plural": "Profile Pictures"},
        ),
        migrations.AlterModelOptions(
            name="smstemplate",
            options={"ordering": ["id"], "verbose_name_plural": "SMS Templates"},
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 8, 9, 42, 6, 647036, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 8, 9, 42, 6, 644277, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 8, 9, 42, 6, 646199, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterModelTable(
            name="emailtemplate",
            table="Email Templates",
        ),
        migrations.AlterModelTable(
            name="oneclickresponse",
            table="One Click Response",
        ),
        migrations.AlterModelTable(
            name="profilepicture",
            table="Profile Pictures",
        ),
        migrations.AlterModelTable(
            name="smstemplate",
            table="SMS Templates",
        ),
    ]
