# Generated by Django 4.1.7 on 2023-05-10 04:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0039_alter_emailtemplate_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="oneclickresponse",
            options={},
        ),
        migrations.RenameField(
            model_name="emailtemplate",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RemoveField(
            model_name="emailtemplate",
            name="created",
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 10, 4, 21, 14, 953613, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="oneclickresponse",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.emailtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 10, 4, 21, 14, 952162, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 10, 4, 21, 14, 953160, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterModelTable(
            name="oneclickresponse",
            table=None,
        ),
    ]
