# Generated by Django 4.1.7 on 2023-05-22 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0040_alter_oneclickresponse_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 22, 8, 52, 31, 689855, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 22, 8, 52, 31, 688254, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 22, 8, 52, 31, 689395, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
