# Generated by Django 4.1.7 on 2023-05-22 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0041_alter_emailtemplate_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 22, 8, 54, 20, 909309, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 22, 8, 54, 20, 891001, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 22, 8, 54, 20, 906326, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
