# Generated by Django 4.1.7 on 2023-05-23 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0044_alter_emailtemplate_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 23, 11, 27, 10, 891520, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 23, 11, 27, 10, 795773, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="smstemplate",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 23, 11, 27, 10, 797470, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
