# Generated by Django 4.1.7 on 2023-04-18 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SetCreditPurchased",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit_amount", models.PositiveIntegerField()),
                ("price_amount", models.FloatField()),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 18, 8, 4, 25, 310439, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 18, 8, 4, 25, 310460, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Set Purchased Credit",
            },
        ),
    ]
