# Generated by Django 4.1.7 on 2023-04-18 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_setcreditpurchased_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setcreditpurchased",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 18, 8, 23, 40, 200032, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="setcreditpurchased",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 18, 8, 23, 40, 200056, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
