# Generated by Django 4.1.7 on 2023-04-18 10:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0003_alter_setcreditpurchased_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setcreditpurchased",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 18, 10, 38, 4, 258765, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="setcreditpurchased",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 18, 10, 38, 4, 258793, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="CreditPurchasedByUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit_amount", models.PositiveIntegerField(default=0)),
                ("credit_price", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("payment_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 18, 10, 38, 4, 259405, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 4, 18, 10, 38, 4, 259419, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_purchased_credit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
