# Generated by Django 4.1.7 on 2023-05-10 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0018_alter_creditpurchasedbyuser_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditpurchasedbyuser",
            options={"verbose_name_plural": "Credit Purchased By Users"},
        ),
        migrations.AlterModelOptions(
            name="setcreditpurchased",
            options={"verbose_name_plural": "Set Purchased Credits"},
        ),
        migrations.AlterField(
            model_name="creditpurchasedbyuser",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 10, 4, 21, 15, 65371, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="creditpurchasedbyuser",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 10, 4, 21, 15, 65386, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="setcreditpurchased",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 10, 4, 21, 15, 64757, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="setcreditpurchased",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 10, 4, 21, 15, 64778, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
