# Generated by Django 4.1.7 on 2023-04-11 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0004_alter_post_created_alter_postlist_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="postlist",
            name="latitude",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="postlist",
            name="longitude",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 11, 7, 4, 30, 404252, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="postlist",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 11, 7, 4, 30, 404922, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="postlist",
            name="location",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
