# Generated by Django 4.1.7 on 2023-04-11 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0007_alter_post_created_alter_postlist_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="postlist",
            name="response_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 11, 10, 31, 37, 349778, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="postlist",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 11, 10, 31, 37, 350741, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
