# Generated by Django 4.1.7 on 2023-04-17 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0015_alter_post_created_alter_postlist_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 17, 9, 34, 17, 457163, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="postlist",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 17, 9, 34, 17, 457830, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
