# Generated by Django 4.1.7 on 2023-04-18 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0024_alter_post_created_alter_postlist_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="myresponse",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 18, 7, 2, 6, 571210, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="postlist",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 18, 7, 2, 6, 571797, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
