# Generated by Django 4.1.7 on 2023-05-02 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0026_alter_post_created_alter_postlist_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="postlist",
            name="is_response",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 2, 6, 14, 26, 931873, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="postlist",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 2, 6, 14, 26, 932473, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
