# Generated by Django 4.1.7 on 2023-05-02 12:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lead", "0027_postlist_is_response_alter_post_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 2, 12, 3, 8, 936456, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="postlist",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 2, 12, 3, 8, 937415, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="RealTimeBookNowService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 5, 2, 12, 3, 8, 941828, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "p_answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="real_time_book_ans",
                        to="lead.answer",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="real_time_book_qs",
                        to="lead.questions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RealTimeBookNow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=500, null=True)),
                ("latitude", models.CharField(blank=True, max_length=500, null=True)),
                ("longitude", models.CharField(blank=True, max_length=500, null=True)),
                ("post_credit", models.IntegerField(blank=True, null=True)),
                ("post_type", models.BooleanField(default=False)),
                ("response_count", models.IntegerField(default=0)),
                ("is_response", models.BooleanField(default=False)),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 5, 2, 12, 3, 8, 942400, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "booked_in_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booked_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="RealTime_service_category",
                        to="lead.category",
                    ),
                ),
                (
                    "realtime_post_object",
                    models.ManyToManyField(
                        blank=True,
                        related_name="RealTime_service_obj",
                        to="lead.realtimebooknowservice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
