# Generated by Django 4.1.7 on 2023-05-23 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0043_alter_creditreducetransaction_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditreducetransaction",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 23, 9, 25, 5, 531479, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 23, 9, 25, 5, 522602, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="postlist",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 23, 9, 25, 5, 523305, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="realtimebooknow",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 23, 9, 25, 5, 529204, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="realtimebooknowservice",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 23, 9, 25, 5, 528498, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
